### ISSUE TITLE
Where are the settings right in the game? 

### ISSUE THREAD

**Issue by QueenUlyana** [Frinn38/Infinite-Music#10]
# #
![2022-01-23_12 21 51](https://user-images.githubusercontent.com/83131824/150672291-6c452658-46ba-43d0-901c-9a721c166b51.png)

**Comment by QueenUlyana** [comment]
And all? Is this the whole list of settings?
![2022-01-23_122528](https://user-images.githubusercontent.com/83131824/150672325-e9010de5-7687-484c-a39f-f9ffc7563539.png)

**Comment by Frinn38** [comment]
Yes, the timer is the only config option.
