### ISSUE TITLE
compatibility issue with other music mod

### ISSUE THREAD

**Issue by EGOIST1372** [Frinn38/Infinite-Music#12]
when I use your mod with [this mod](https://www.curseforge.com/minecraft/mc-mods/music-control) my game freezes couple seconds when a new song plays when the previous song ends by its own doesn't happen when i switch songs with it
and sometimes when a music starts after a few seconds it changes to the next song even though the previous song is not finished yet
both mod runs good without each other but together not working good

**Comment by EGOIST1372** [comment]
you might ask why i use both mod together, well yours has the ability to change song even when I'm in title screen but with that mod its more convenient in-game to use

**Comment by Frinn38** [comment]
I guess both mods fight for changing the same chunk of vanilla code... Can't really do much to fix that, my advise is to remove infinite music since the other mod can basically do the same with more options.
I will add in the mod description that they are not compatible.
