### ISSUE TITLE
Feature: 1.18 support

### ISSUE THREAD

**Issue by TrillionDeTurtle** [Frinn38/Infinite-Music#4]
are you able to make a 1.18 port of this mod

**Comment by K0-RR** [comment]
There is no 1.18 yet? If you are thinking about playing on the experimental snapshots you should know this is a pretty bad idea. Those are experiments - meant to only showcase future updates and get feedback. They are not the standard snapshots we all know. The Nether and End are broken and the whole performance is bad. Things are changing rapidly between these experiments too.

**Comment by TrillionDeTurtle** [comment]
> There is no 1.18 yet? If you are thinking about playing on the experimental snapshots you should know this is a pretty bad idea. Those are experiments - meant to only showcase future updates and get feedback. They are not the standard snapshots we all know. The Nether and End are broken and the whole performance is bad. Things are changing rapidly between these experiments too.

so I understand that there is all the "there is no support" and "it has bad performance" but, there are sodium and iris ports making it **feel** smoother and more polished even if they are doing nothing to make the actual game run smoother however I have managed to get a solid 80fps running 24 render distance on an experimental snapshot version. I have also managed to port the mod over to 1.18 myself by editing files which I hope is acceptable.

**Comment by Frinn38** [comment]
I will wait for at least the "normal" snapshots to update the mod to 1.18 (for fabric since forge doesn't do snapshots). As RDKRACZ mentioned the code change rapidly between snapshots and I don't have the time to update the mod each week.
No problem if you want to build your own modified version of the mod.

**Comment by Ivan-Khar** [comment]
I updated this mod for 1.18
https://github.com/AquUpd/Infinite-Music/tree/Fabric-1.18
