### ISSUE TITLE
Update to 1.18

### ISSUE THREAD

**Issue by Ivan-Khar** [Frinn38/Infinite-Music#5]
https://github.com/AquUpd/Infinite-Music/tree/Fabric-1.18
I made 1.18 version, I can't PR it because you don't have Fabric-1.18 branch

**Comment by Ivan-Khar** [comment]
And I don't know how to PR new branches

**Comment by Frinn38** [comment]
That's probably possible, but I don't know how too x)
Anyway I just created a Fabric-1.18 branch, you can PR your changes to it.

**Comment by Ivan-Khar** [comment]
Thanks
