### ISSUE TITLE
Mod crashes servers due to using sided code in main mod class.

### ISSUE THREAD

**Issue by Claycorp** [Frinn38/Infinite-Music#7]
Your mod currently crashes when installed on servers as you are calling client code in the main class of the mod.
Mods should be only handling side agnostic code in the main class to prevent sided crashes.

Please follow the modding standard of handling sides correctly so pack devs and server owners don't need to hunt down issues.

**Comment by Ivan-Khar** [comment]
It's client side mod, isn't it? Why do you need to install it in servers

**Comment by Claycorp** [comment]
I wouldn't know. Not my mod, nor do I use it in my own projects.

If I go to install a modpack on a server I shouldn't need to play the "let's find the mod that was made incorrectly" game multiple times to get it started due to developers ignoring/not knowing the fact that sides exist. If they don't know, then this is the point for them to learn about it.

**Comment by AquUpd** [comment]
why do you put this mod in server? it's just client side mod

**Comment by Frinn38** [comment]
Fixed in last update.

**Comment by Claycorp** [comment]
Thanks!
