### ISSUE TITLE
mods.toml is incomplete

### ISSUE THREAD

**Issue by Claycorp** [Frinn38/Infinite-Music#8]
Your `mods.toml` is incomplete.
Please either remove or fill out the parts tagged with `#optional` as things like the issue tracker is used in handling of some crashes.
https://github.com/Frinn38/Infinite-Music/blob/a32f5cf58d75a4ce46d670cfb35af99e15c2dc19/src/main/resources/META-INF/mods.toml#L10-L11

**Comment by Frinn38** [comment]
Fixed in last update.
